default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 

development:
  <<: *default
  database: harbour_development

test:
  <<: *default
  database: harbour_test

staging:
  <<: *default
  database: harbour_staging
  password: root

production:
  <<: *default
  password: <%= ENV["DB_PASSWORD"] %>
  database: harbour_production
